arrowParens: "avoid"
bracketSameLine: true
bracketSpacing: true
htmlWhitespaceSensitivity: "css"
proseWrap: "preserve"
quoteProps: "consistent"
semi: true
singleAttributePerLine: false
singleQuote: false
trailingComma: "es5"
useTabs: false
overrides:
  # JSON
  - files: [".*rc"]
    options:
      parser: "json"
      trailingComma: "es5"
